export const filterOptions = {
  houses: [
    "BFSportsbook",
    "Bet365",
    "Bet7k",
    "BetFast",
    "BetNacional",
    "Betano",
    "Betfair",
    "Betsson",
    "Betway",
    "Blaze",
    "Estrelabet",
    "Kto",
    "Matchbook",
    "Novibet",
    "Pinnacle",
    "Rivalo",
    "Sbobet",
    "Sportingbet",
    "Superbet",
    "Vbet",
    "10Game",
    "6R",
    "7Games",
    "9D",
    "9F",
    "Aposta1",
    "ApostaMax",
    "ApostaTudo",
    "B2XBet",
    "BR4",
    "BateuBet",
    "Bateguebet",
    "BetAki",
    "BetApp",
    "BetBra Exchange",
    "BetBuffalos",
    "BetDaSorte",
    "BetFalcons",
    "BetFusion",
    "BetGorillas",
    "BetPark",
    "BetPontoBet",
    "BetVip",
    "Betboo",
    "Betmgm",
    "Betou",
    "Betwarrior",
    "Betão",
    "BolsaDeApostas",
    "BravoBet",
    "BullsBet",
    "CassinoBet",
    "DonaldBet",
    "EsportivaBet",
    "Faz1Bet",
    "FulltBet",
    "GolDeBet",
    "H2Bet",
    "JogoDeOuro",
    "Jogão",
    "JonBet",
    "LotoGreen",
    "Lottoland",
    "MaximaBet",
    "McGames",
    "MultiBet",
    "P9",
    "Pagol",
    "Pixbet",
    "R7",
    "RicoBet",
    "Rivalry",
    "SeguroBet",
    "Seubet",
    "SorteNaBet",
    "SorteOnline",
    "Stake Br",
    "SupremaBet",
    "TivoBet",
    "UltraBet",
    "VeraBet",
    "WjCasino"
  ],
  currencies: [
    {
      "code": "USD",
      "label": "USD"
    },
    {
      "code": "EUR",
      "label": "EUR"
    },
    {
      "code": "BRL",
      "label": "BRL"
    },
    {
      "code": "PEN",
      "label": "PEN"
    }
  ],
  sports: [
    { value: "Artes marciais", label: "Artes marciais" },
    { value: "Badminton", label: "Badminton" },
    { value: "Bandy", label: "Bandy" },
    { value: "Basquete", label: "Basquete" },
    { value: "Beisebol", label: "Beisebol" },
    { value: "Biatlo", label: "Biatlo" },
    { value: "Boxe", label: "Boxe" },
    { value: "Ciclismo", label: "Ciclismo" },
    { value: "Corrida de cavalos", label: "Corrida de cavalos" },
    { value: "Críquete", label: "Críquete" },
    { value: "Curling", label: "Curling" },
    { value: "Dardos", label: "Dardos" },
    { value: "Esporte a motor", label: "Esporte a motor" },
    { value: "Esporte gaélico", label: "Esporte gaélico" },
    { value: "Floorball", label: "Floorball" },
    { value: "Futebol", label: "Futebol" },
    { value: "Futebol americano", label: "Futebol americano" },
    { value: "Futebol australiano", label: "Futebol australiano" },
    { value: "Futebol de praia", label: "Futebol de praia" },
    { value: "Futsal", label: "Futsal" },
    { value: "Fórmula 1", label: "Fórmula 1" },
    { value: "Golfe", label: "Golfe" },
    { value: "Handebol", label: "Handebol" },
    { value: "Hurling", label: "Hurling" },
    { value: "Hóquei", label: "Hóquei" },
    { value: "Hóquei em campo", label: "Hóquei em campo" },
    { value: "Lacrosse", label: "Lacrosse" },
    { value: "MMA", label: "MMA" },
    { value: "Netball", label: "Netball" },
    { value: "Polo aquático", label: "Polo aquático" },
    { value: "Rugby league", label: "Rugby league" },
    { value: "Rugby union", label: "Rugby union" },
    { value: "Sinuca", label: "Sinuca" },
    { value: "Squash", label: "Squash" },
    { value: "Tênis", label: "Tênis" },
    { value: "Tênis de mesa", label: "Tênis de mesa" },
    { value: "Vôlei", label: "Vôlei" },
    { value: "Vôlei de praia", label: "Vôlei de praia" },
    { value: "Vôlei kung-fu", label: "Vôlei kung-fu" },
    { value: "Xadrez", label: "Xadrez" }
  ]
}
